version: "3"
services:
  ldap:
    build:
      context: openldap
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    domainname: "mycompany.com"
    hostname: "mycompany.com"
    environment:
#      LDAP_SEED_INTERNAL_LDIF_PATH: "/data/data.ldif"# env var set in openldap/Dockerfile
      LDAP_DOMAIN: mycompany.com
      LDAP_ORGANISATION: "My company"
      LDAP_ADMIN_PASSWORD: admin #login DN: cn=admin,dc=mycompany,dc=com
    ports:
      - 389:389
    volumes:
    - ./ldap-data/ldap:/var/lib/ldap
    - ./ldap-data/slapd.d:/etc/ldap/slapd.d
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8089:80"
    depends_on:
      - ldap
  php:
    build:
      context: php
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    working_dir: /app
    links:
      - ldap:ldap
    depends_on:
      - ldap
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ./app:/app